disabled_rules:
        - function_body_length
        - closing_brace
        - statement_position
        - force_cast
        - force_try
        - variable_name
included:
        - Highball
line_length: 200
